name: Github Pages CD
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: "Step1: Checkout"
      uses: actions/checkout@v1

    - name: "Step2: Setup Node"
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: "Step3: Build"
      run: |
        npm -v
        npm install
        npm run build

    - name: "Step4: Deploy"
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        folder: .vuepress/dist
        branch: master
